name: release-binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }} binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install . pyinstaller
      - name: Build binary
        run: pyinstaller wiki_extractor/cli.py --name wiki-extractor --onefile

      - name: Rename binary for release
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            mv dist/wiki-extractor dist/wiki-extractor-linux
          elif [ "${{ runner.os }}" == "macOS" ]; then
            mv dist/wiki-extractor dist/wiki-extractor-macos
          elif [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/wiki-extractor.exe dist/wiki-extractor-windows.exe
          fi
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/wiki-extractor-*
